# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-15 06:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bname', models.CharField(max_length=20, verbose_name='物资名称')),
                ('btext', models.CharField(max_length=50, verbose_name='物资描述')),
                ('btime', models.DateTimeField(auto_now_add=True, verbose_name='购买时间')),
            ],
        ),
        migrations.CreateModel(
            name='laboratory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=20, verbose_name='实验室名称')),
                ('floor', models.IntegerField(verbose_name='楼层')),
                ('room_num', models.CharField(max_length=20, verbose_name='房间号')),
                ('lbalance', models.ManyToManyField(to='djangoapp1.Balance')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('passwd', models.CharField(max_length=20)),
                ('uname', models.CharField(max_length=6)),
            ],
        ),
        migrations.AddField(
            model_name='laboratory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoapp1.User', verbose_name='负责人'),
        ),
        migrations.AddField(
            model_name='balance',
            name='buser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance', to='djangoapp1.User', verbose_name='购买人'),
        ),
    ]
