# Generated by Django 2.2 on 2019-12-29 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20191228_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseexpire',
            name='text',
            field=models.CharField(default='3天有效', help_text='文本提示', max_length=100, verbose_name='文本提示'),
        ),
        migrations.AlterField(
            model_name='courseexpire',
            name='expire',
            field=models.CharField(help_text='课程有效期', max_length=100, verbose_name='课程有效期(天)'),
        ),
    ]
