# Generated by Django 2.2 on 2020-01-03 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20200103_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='orders',
            field=models.IntegerField(default=0, verbose_name='显示顺序'),
        ),
        migrations.AlterField(
            model_name='course',
            name='orders',
            field=models.IntegerField(default=0, verbose_name='显示顺序'),
        ),
        migrations.AlterField(
            model_name='courseactivity',
            name='orders',
            field=models.IntegerField(default=0, verbose_name='显示顺序'),
        ),
        migrations.AlterField(
            model_name='coursecategory',
            name='orders',
            field=models.IntegerField(default=0, verbose_name='显示顺序'),
        ),
        migrations.AlterField(
            model_name='coursechapter',
            name='orders',
            field=models.IntegerField(default=0, verbose_name='显示顺序'),
        ),
        migrations.AlterField(
            model_name='courseexpire',
            name='orders',
            field=models.IntegerField(default=0, verbose_name='显示顺序'),
        ),
        migrations.AlterField(
            model_name='courselesson',
            name='orders',
            field=models.IntegerField(default=0, verbose_name='显示顺序'),
        ),
        migrations.AlterField(
            model_name='pricediscount',
            name='orders',
            field=models.IntegerField(default=0, verbose_name='显示顺序'),
        ),
        migrations.AlterField(
            model_name='pricediscounttype',
            name='orders',
            field=models.IntegerField(default=0, verbose_name='显示顺序'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='orders',
            field=models.IntegerField(default=0, verbose_name='显示顺序'),
        ),
    ]
