# Generated by Django 2.2 on 2020-01-03 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orders',
            field=models.IntegerField(default=0, verbose_name='显示顺序'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='orders',
            field=models.IntegerField(default=0, verbose_name='显示顺序'),
        ),
    ]
